### ISSUE TITLE
Display Firmware Availability

### ISSUE THREAD

**Issue by Dawserdoos** [freewili/freewili-firmware#1]
I've made a very silly mistake. I had accidentally gotten the device into it's Display Firmware update mode without thinking and ended up flashing the Main firmware to the Display device. I still have USB connection for firmware updates when I connect it to a PC.

I was wondering when the Display Firmware will become available, as I believe that should be all that's needed to repair the device.

**Comment by drebbe-intrepid** [comment]
PR #2

**Comment by drebbe-intrepid** [comment]
https://github.com/freewili/freewili-firmware/releases/tag/v29_main
